### ISSUE TITLE
Android : Preview Orientation is rotated 90 and streched on Android 5 tablets

### ISSUE THREAD

**Issue by packedbox** [EnoxSoftware/NatCamWithOpenCVForUnityExample#6]
Hi, I Tested with NatCamWithOpenCVForUnityExample_v2.3.0.apk

The camera preview is Rotated and streched on Android 5 tablets 

![Screenshot_20191022-140446](https://user-images.githubusercontent.com/1764662/67284453-e47b2d80-f4d5-11e9-8af0-7172254379f8.png)

On android 9 I can correct it by clicking stop then play and its fixes the orientation after a phone change of orientation but on Android 5 the rotation and stretch is always wrong and the stop / play does not fix it.

**Comment by EnoxSoftware** [comment]
Did you encounter the problem in the NatCamPreviewOnlyExample scene?
If so, the problem is probably due to the NatCam Asset.
My example is to display a raw camera image obtained from NatCam. (Image orientation rotation processing is not included)
If possible, can you try the simpler example scene that comes with NatCam's Asset?
Maybe the same problem should occur.
